# Generated by Django 4.2.1 on 2023-05-25 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('direct_messages', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattingroom',
            name='user',
            field=models.ManyToManyField(related_name='direct_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to='direct_messages.chattingroom'),
        ),
    ]
